### ISSUE TITLE
【Swagger导入报错】版本0-10，在导入Swagger V2 JSON文件时，报错

### ISSUE THREAD

**Issue by junjuntj** [brookshi/Hitchhiker#142]
麻烦大神们帮忙看下一下错误！
我的swagger文件是通过http://ip:port/v2/api-docs得到
[2018-03-28 16:33:47.474] [ERROR] default - TypeError: Cannot read property 'length' of undefined
    at SwaggerImport.parseUrl (/data1/Hitchhiker/api/services/importer/swagger_import.ts:94:29)
    at _.keys.map.method (/data1/Hitchhiker/api/services/importer/swagger_import.ts:83:27)
    at Array.map (native)
    at SwaggerImport.createRecordsForFolder (/data1/Hitchhiker/api/services/importer/swagger_import.ts:74:36)
    at _.keys.forEach.path (/data1/Hitchhiker/api/services/importer/swagger_import.ts:55:40)
    at Array.forEach (native)
    at SwaggerImport.createRecords (/data1/Hitchhiker/api/services/importer/swagger_import.ts:45:35)
    at SwaggerImport.<anonymous> (/data1/Hitchhiker/api/services/importer/swagger_import.ts:35:35)
    at Generator.next (<anonymous>)
    at fulfilled (/data1/Hitchhiker/build/services/importer/swagger_import.js:4:58)

**Comment by brookshi** [comment]
异常是没有schemes这个节点，我是用官方文档做的参考来导入的，可能你那边导出的文档不太一样。
官方的例子：http://petstore.swagger.io/
根节点下有个"schemes": ["http"],要不你加上试试

**Comment by junjuntj** [comment]
的确是这原因，非常感谢
