### ISSUE TITLE
中文模式下编码异常

### ISSUE THREAD

**Issue by gumutianqi** [brookshi/Hitchhiker#148]
```
2018/4/9 下午2:08:14[2018-04-09 06:08:14.176] [ERROR] console - 
2018/4/9 下午2:08:14[2018-04-09 06:08:14.176] [ERROR] console -   Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE6\x96\xB0\xE9\xA1\xB9...' for column 'name' at row 1
2018/4/9 下午2:08:14      at Query.Sequence._packetToError (/usr/src/Hitchhiker/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
2018/4/9 下午2:08:14      at Query.ErrorPacket (/usr/src/Hitchhiker/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
2018/4/9 下午2:08:14      at Protocol._parsePacket (/usr/src/Hitchhiker/node_modules/mysql/lib/protocol/Protocol.js:280:23)
2018/4/9 下午2:08:14      at Parser.write (/usr/src/Hitchhiker/node_modules/mysql/lib/protocol/Parser.js:75:12)
2018/4/9 下午2:08:14      at Protocol.write (/usr/src/Hitchhiker/node_modules/mysql/lib/protocol/Protocol.js:39:16)
2018/4/9 下午2:08:14      at Socket.<anonymous> (/usr/src/Hitchhiker/node_modules/mysql/lib/Connection.js:103:28)
2018/4/9 下午2:08:14      at emitOne (events.js:96:13)
2018/4/9 下午2:08:14      at Socket.emit (events.js:191:7)
2018/4/9 下午2:08:14      at readableAddChunk (_stream_readable.js:178:18)
2018/4/9 下午2:08:14      at Socket.Readable.push (_stream_readable.js:136:10)
2018/4/9 下午2:08:14      at TCP.onread (net.js:561:20)
2018/4/9 下午2:08:14      --------------------
2018/4/9 下午2:08:14      at Protocol._enqueue (/usr/src/Hitchhiker/node_modules/mysql/lib/protocol/Protocol.js:141:48)
2018/4/9 下午2:08:14      at PoolConnection.query (/usr/src/Hitchhiker/node_modules/mysql/lib/Connection.js:208:25)
2018/4/9 下午2:08:14      at MysqlQueryRunner.<anonymous> (/usr/src/Hitchhiker/src/driver/mysql/MysqlQueryRunner.ts:160:32)
2018/4/9 下午2:08:14      at step (/usr/src/Hitchhiker/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
2018/4/9 下午2:08:14      at Object.next (/usr/src/Hitchhiker/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
2018/4/9 下午2:08:14      at fulfilled (/usr/src/Hitchhiker/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:4:58)
2018/4/9 下午2:08:14      at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by gumutianqi** [comment]
新增 mysql.cnf 文件后正常
