### ISSUE TITLE
自动化测试 project libs 失效

### ISSUE THREAD

**Issue by yaming116** [brookshi/Hitchhiker#152]
单个用例执行和自动化测试手动执行l都ib是生效，但是定时执行时候会报错，找不到当前libs

```
[2018-04-10 01:26:48.069] [ERROR] default - Error: no valid js lib named [qs], you should upload this lib first.
    at Sandbox.require (/usr/src/Hitchhiker/build/run_engine/sandbox.js:65:19)
    at Object.apply (/usr/src/Hitchhiker/node_modules/vm2/lib/contextify.js:288:34)
    at vm.js:7:35
    at module.exports (vm.js:34:22)
    at Object.apply (/usr/src/Hitchhiker/node_modules/vm2/lib/contextify.js:87:36)
    at Promise (/usr/src/Hitchhiker/build/run_engine/script_runner.js:76:17)
    at Function.run (/usr/src/Hitchhiker/build/run_engine/script_runner.js:75:20)
    at Function.<anonymous> (/usr/src/Hitchhiker/build/run_engine/script_runner.js:50:44)
    at Generator.next (<anonymous>)
    at /usr/src/Hitchhiker/build/run_engine/script_runner.js:7:71

```

**Comment by yaming116** [comment]
项目手动重新一下，lib生效了

**Comment by brookshi** [comment]
这个看起来是个bug，我查下哈，谢谢
