### ISSUE TITLE
导入postman用例抛异常

### ISSUE THREAD

**Issue by yrong** [brookshi/Hitchhiker#19]
```
[2017-09-29 15:16:55.292] [ERROR] console -   Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xE6\xB5\x8B\xE8\xAF\x95...' for column 'body' at row 1
      at Query.Sequence._packetToError (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
      at Query.ErrorPacket (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
      at Protocol._parsePacket (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/protocol/Parser.js:75:12)
      at Protocol.write (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/Connection.js:103:28)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:191:7)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at TCP.onread (net.js:561:20)
      --------------------


      at Protocol._enqueue (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/protocol/Protocol.js:141:48)
      at PoolConnection.query (/ssd/mynode/Hitchhiker/node_modules/mysql/lib/Connection.js:208:25)
      at MysqlQueryRunner.<anonymous> (/ssd/mynode/Hitchhiker/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:180:44)
      at step (/ssd/mynode/Hitchhiker/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:32:23)
      at Object.next (/ssd/mynode/Hitchhiker/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:13:53)
      at fulfilled (/ssd/mynode/Hitchhiker/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:109:7)
[2017-09-29 15:16:55.292] [ERROR] console - 
```

**Comment by yrong** [comment]
[cmdb.postman_collection.json.zip](https://github.com/brookshi/Hitchhiker/files/1343399/cmdb.postman_collection.json.zip)

**Comment by brookshi** [comment]
看起来是数据库没有设置utf-8，我本地可以导进来
![image](https://user-images.githubusercontent.com/13607728/31006155-2910aae6-a52e-11e7-9017-34d6db5cd1ec.png)

部署文档里有提到这点：
>创建DB: CREATE DATABASE IF NOT EXISTS `hitchhiker-prod` default charset utf8 COLLATE utf8_general_ci; 修改变量需要把max_allowed_packet=200M加到 /my.conf 文件[mysqld] Section下，具体参考：[change max_allowed_packet](https://stackoverflow.com/questions/8062496/how-to-change-max-allowed-packet-size)

**Comment by yrong** [comment]
谢谢，不过目录结构好像没有保留
5-1,5-2应该是在5之下的子目录
![2017-09-29 16-15-21](https://user-images.githubusercontent.com/4383920/31006959-716c7ab0-a531-11e7-823a-469a9534ca65.png)

**Comment by brookshi** [comment]
这个现在还不支持多级目录。。，本来是打算支持的，看postman没做，我也就没搞了，后来postman又加上了，  打算回头也加上，暂时只能用一级目录了

**Comment by yrong** [comment]
是否可以兼容postman的运行期环境变量设置函数
![2017-09-30 10-31-47](https://user-images.githubusercontent.com/4383920/31041615-e225a396-a5ca-11e7-8f88-30f828ab6647.png)
另外现在通过batch edit拷贝粘贴方式导入原postman的环境变量还是不太方便，最好可以直接导入文件

**Comment by brookshi** [comment]
嗯，可以在后面版本加进来变量设置函数转成hitchhiker这边的，导入环境也是，都加到计划中，谢谢。

**Comment by vmvz** [comment]
@brookshi 可能多级目录会更好一些.

![image](https://user-images.githubusercontent.com/1652700/37214546-59bee338-23f0-11e8-9b89-466df50ec615.png)
