### ISSUE TITLE
部署后，浏览器访问时界面白屏

### ISSUE THREAD

**Issue by poipo** [brookshi/Hitchhiker#201]
部署后，
![image](https://user-images.githubusercontent.com/24470435/41266414-59478666-6e29-11e8-80b7-8ebd6b55ddf6.png)

页面白屏
日志如下
[2018-06-12 10:16:53.312] [INFO] default - create process manager for C:\Users\v-panzw02\Desktop\hitchhiker0.12\build\run_engine\process\stress_nodejs_worker.js
[2018-06-12 10:16:53.354] [INFO] default - stress nodejs worker process created
[2018-06-12 10:16:53.386] [INFO] default - stress nodejs worker process created
[2018-06-12 10:16:53.433] [INFO] default - stress nodejs worker process created
[2018-06-12 10:16:53.513] [INFO] default - stress nodejs worker process created
[2018-06-12 10:16:54.532] [ERROR] default - nodejs stress process - error: Error: connect ECONNREFUSED 127.0.0.1:11010
[2018-06-12 10:16:54.532] [ERROR] default - nodejs stress process - close 1006: 
[2018-06-12 10:16:54.532] [INFO] default - will retry.
[2018-06-12 10:16:55.806] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'hitchhiker-prod' AND TABLE_NAME IN ('header', 'query_string', 'record_doc_history', 'record_doc', 'record_history', 'body_form_data', 'record', 'collection', 'localhost_mapping', 'variable', 'environment', 'project', 'user', 'schedule_record', 'schedule', 'stress', 'stress_record', 'stress_failed_info', 'project_members_user')
[2018-06-12 10:16:55.811] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hitchhiker-prod'
[2018-06-12 10:16:55.811] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = 'hitchhiker-prod' AND INDEX_NAME != 'PRIMARY'
[2018-06-12 10:16:55.812] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'hitchhiker-prod' AND REFERENCED_COLUMN_NAME IS NOT NULL
[2018-06-12 10:16:55.951] [DEBUG] default - SHOW INDEX FROM `body_form_data` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `collection` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `environment` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `header` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `localhost_mapping` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `project` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `project_members_user` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `query_string` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `record` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `record_doc` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `record_doc_history` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `record_history` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.952] [DEBUG] default - SHOW INDEX FROM `schedule` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.953] [DEBUG] default - SHOW INDEX FROM `schedule_record` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.953] [DEBUG] default - SHOW INDEX FROM `stress` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.953] [DEBUG] default - SHOW INDEX FROM `stress_failed_info` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.953] [DEBUG] default - SHOW INDEX FROM `stress_record` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.953] [DEBUG] default - SHOW INDEX FROM `user` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.953] [DEBUG] default - SHOW INDEX FROM `variable` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:55.969] [DEBUG] default - START TRANSACTION
[2018-06-12 10:16:55.977] [DEBUG] default - columns changed in schedule_record. updating: runDate
[2018-06-12 10:16:55.980] [DEBUG] default - ALTER TABLE `schedule_record` CHANGE `runDate` `runDate` datetime NOT NULL DEFAULT '1949-10-01'
[2018-06-12 10:16:55.996] [DEBUG] default - COMMIT
[2018-06-12 10:16:56.889] [INFO] default - stress process start
[2018-06-12 10:16:56.892] [INFO] default - stress - create socket server
[2018-06-12 10:16:56.900] [INFO] default - stress - user message
[2018-06-12 10:16:56.900] [INFO] default - stress - user start
[2018-06-12 10:16:56.710] [INFO] default - schedule start.
[2018-06-12 10:16:56.716] [INFO] default - get all schedule.
[2018-06-12 10:16:57.163] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'hitchhiker-prod' AND TABLE_NAME IN ('schedule_record', 'schedule', 'localhost_mapping', 'variable', 'environment', 'project', 'user', 'collection', 'header', 'query_string', 'record_doc_history', 'record_doc', 'record_history', 'body_form_data', 'record', 'stress', 'stress_record', 'stress_failed_info', 'project_members_user')
[2018-06-12 10:16:57.167] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'hitchhiker-prod'
[2018-06-12 10:16:57.167] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = 'hitchhiker-prod' AND INDEX_NAME != 'PRIMARY'
[2018-06-12 10:16:57.167] [DEBUG] default - SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = 'hitchhiker-prod' AND REFERENCED_COLUMN_NAME IS NOT NULL
[2018-06-12 10:16:57.207] [DEBUG] default - SHOW INDEX FROM `body_form_data` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.207] [DEBUG] default - SHOW INDEX FROM `collection` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.207] [DEBUG] default - SHOW INDEX FROM `environment` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.207] [DEBUG] default - SHOW INDEX FROM `header` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `localhost_mapping` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `project` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `project_members_user` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `query_string` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `record` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `record_doc` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `record_doc_history` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `record_history` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `schedule` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `schedule_record` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `stress` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `stress_failed_info` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `stress_record` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `user` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.208] [DEBUG] default - SHOW INDEX FROM `variable` WHERE Key_name = 'PRIMARY'
[2018-06-12 10:16:57.225] [DEBUG] default - START TRANSACTION
[2018-06-12 10:16:57.232] [DEBUG] default - columns changed in schedule_record. updating: runDate
[2018-06-12 10:16:57.235] [DEBUG] default - ALTER TABLE `schedule_record` CHANGE `runDate` `runDate` datetime NOT NULL DEFAULT '1949-10-01'
[2018-06-12 10:16:57.249] [DEBUG] default - COMMIT
[2018-06-12 10:16:57.260] [DEBUG] default - SELECT `Schedule`.`id` AS `Schedule_id`, `Schedule`.`name` AS `Schedule_name`, `Schedule`.`collectionId` AS `Schedule_collectionId`, `Schedule`.`environmentId` AS `Schedule_environmentId`, `Schedule`.`needCompare` AS `Schedule_needCompare`, `Schedule`.`compareEnvironmentId` AS `Schedule_compareEnvironmentId`, `Schedule`.`timer` AS `Schedule_timer`, `Schedule`.`period` AS `Schedule_period`, `Schedule`.`hour` AS `Schedule_hour`, `Schedule`.`notification` AS `Schedule_notification`, `Schedule`.`emails` AS `Schedule_emails`, `Schedule`.`needOrder` AS `Schedule_needOrder`, `Schedule`.`recordsOrder` AS `Schedule_recordsOrder`, `Schedule`.`suspend` AS `Schedule_suspend`, `Schedule`.`ownerId` AS `Schedule_ownerId`, `Schedule`.`lastRunDate` AS `Schedule_lastRunDate`, `Schedule`.`createDate` AS `Schedule_createDate`, `Schedule`.`updateDate` AS `Schedule_updateDate` FROM `schedule` `Schedule` WHERE `Schedule`.`suspend`=? -- PARAMETERS: [false]
[2018-06-12 10:16:57.262] [INFO] default - root schedules length is 0
[2018-06-12 10:16:57.262] [INFO] default - schedules length is 0.
[2018-06-12 10:16:58.898] [INFO] default - worker 15612 start
[2018-06-12 10:16:59.046] [INFO] default - worker 12184 start
[2018-06-12 10:16:59.153] [INFO] default - worker 9028 start
[2018-06-12 10:16:59.249] [INFO] default - worker 11324 start
[2018-06-12 10:17:04.542] [INFO] default - stress - worker connected: ::ffff:127.0.0.1
[2018-06-12 10:17:04.544] [INFO] default - nodejs stress process - connect success
[2018-06-12 10:17:04.544] [INFO] default - nodejs stress process - send message with type 0 and status: 0
[2018-06-12 10:17:04.546] [INFO] default - stress - data from ::ffff:127.0.0.1: "{\"status\":0,\"type\":0,\"runResult\":null,\"cpuNum\":4}"
[2018-06-12 10:17:04.547] [INFO] default - stress - hardware
[2018-06-12 10:17:04.547] [INFO] default - stress 5 - broadcast msg to user
[2018-06-12 10:17:56.979] [INFO] default - schedule start.
[2018-06-12 10:17:56.979] [INFO] default - get all schedule.
[2018-06-12 10:17:56.982] [DEBUG] default - SELECT `Schedule`.`id` AS `Schedule_id`, `Schedule`.`name` AS `Schedule_name`, `Schedule`.`collectionId` AS `Schedule_collectionId`, `Schedule`.`environmentId` AS `Schedule_environmentId`, `Schedule`.`needCompare` AS `Schedule_needCompare`, `Schedule`.`compareEnvironmentId` AS `Schedule_compareEnvironmentId`, `Schedule`.`timer` AS `Schedule_timer`, `Schedule`.`period` AS `Schedule_period`, `Schedule`.`hour` AS `Schedule_hour`, `Schedule`.`notification` AS `Schedule_notification`, `Schedule`.`emails` AS `Schedule_emails`, `Schedule`.`needOrder` AS `Schedule_needOrder`, `Schedule`.`recordsOrder` AS `Schedule_recordsOrder`, `Schedule`.`suspend` AS `Schedule_suspend`, `Schedule`.`ownerId` AS `Schedule_ownerId`, `Schedule`.`lastRunDate` AS `Schedule_lastRunDate`, `Schedule`.`createDate` AS `Schedule_createDate`, `Schedule`.`updateDate` AS `Schedule_updateDate` FROM `schedule` `Schedule` WHERE `Schedule`.`suspend`=? -- PARAMETERS: [false]
[2018-06-12 10:17:56.983] [INFO] default - root schedules length is 0
[2018-06-12 10:17:56.984] [INFO] default - schedules length is 0.

麻烦帮我看一下，谢谢

**Comment by poipo** [comment]
昨天都能用的，今早就这样了。。。

**Comment by brookshi** [comment]
pm2 logs看下

**Comment by poipo** [comment]
PS C:\Users\v-panzw02\Desktop\hitchhiker0.12\build> pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
C:\Users\v-panzw02\.pm2\pm2.log last 15 lines:
PM2        | [2018-06-12 10:49:33] PM2 log: Time                 : Tue Jun 12 2018 10:49:33 GMT+0800 (中国标准时间)
PM2        | [2018-06-12 10:49:33] PM2 log: PM2 version          : 2.10.2
PM2        | [2018-06-12 10:49:33] PM2 log: Node.js version      : 8.11.1
PM2        | [2018-06-12 10:49:33] PM2 log: Current arch         : x64
PM2        | [2018-06-12 10:49:33] PM2 log: PM2 home             : C:\Users\v-panzw02\.pm2
PM2        | [2018-06-12 10:49:33] PM2 log: PM2 PID file         : C:\Users\v-panzw02\.pm2\pm2.pid
PM2        | [2018-06-12 10:49:33] PM2 log: RPC socket file      : \\.\pipe\rpc.sock
PM2        | [2018-06-12 10:49:33] PM2 log: BUS socket file      : \\.\pipe\pub.sock
PM2        | [2018-06-12 10:49:33] PM2 log: Application log path : C:\Users\v-panzw02\.pm2\logs
PM2        | [2018-06-12 10:49:33] PM2 log: Process dump file    : C:\Users\v-panzw02\.pm2\dump.pm2
PM2        | [2018-06-12 10:49:33] PM2 log: Concurrent actions   : 2
PM2        | [2018-06-12 10:49:33] PM2 log: SIGTERM timeout      : 1600
PM2        | [2018-06-12 10:49:33] PM2 log: ===============================================================================
PM2        | [2018-06-12 10:49:35] PM2 log: Starting execution sequence in -fork mode- for app name:hitchhiker id:0
PM2        | [2018-06-12 10:49:35] PM2 log: App name:hitchhiker id:0 online

C:\Users\v-panzw02\.pm2\logs\hitchhiker-error-0.log last 15 lines:
0|hitchhik |     at Object.<anonymous> (C:\Users\v-panzw02\Desktop\hitchhiker0.11\api\services\project_data_service.ts:17:43)
0|hitchhik |     at Module._compile (module.js:652:30)
0|hitchhik |     at Object.Module._extensions..js (module.js:663:10)
0|hitchhik |     at Module.load (module.js:565:32)
0|hitchhik | Error: ENOENT: no such file or directory, mkdir 'C:\Users\v-panzw02\Desktop\hitchhiker0.11\build\global_data\cryptojs.zip\lib'
0|hitchhik |     at Object.fs.mkdirSync (fs.js:885:18)
0|hitchhik |     at ProjectDataService.initFolderFiles (C:\Users\v-panzw02\Desktop\hitchhiker0.11\api\services\project_data_service.ts:131:16)
0|hitchhik |     at projectFolders.forEach.folder (C:\Users\v-panzw02\Desktop\hitchhiker0.11\api\services\project_data_service.ts:142:18)
0|hitchhik |     at Array.forEach (<anonymous>)
0|hitchhik |     at ProjectDataService.initProjectFiles (C:\Users\v-panzw02\Desktop\hitchhiker0.11\api\services\project_data_service.ts:141:24)
0|hitchhik |     at new ProjectDataService (C:\Users\v-panzw02\Desktop\hitchhiker0.11\api\services\project_data_service.ts:29:14)
0|hitchhik |     at Object.<anonymous> (C:\Users\v-panzw02\Desktop\hitchhiker0.11\api\services\project_data_service.ts:17:43)
0|hitchhik |     at Module._compile (module.js:652:30)
0|hitchhik |     at Object.Module._extensions..js (module.js:663:10)
0|hitchhik |     at Module.load (module.js:565:32)

C:\Users\v-panzw02\.pm2\logs\hitchhiker-out-0.log last 15 lines:
0|hitchhik |     at process._tickCallback (internal/process/next_tick.js:188:7)
0|hitchhik | [2018-06-01 09:29:23.264] [ERROR] console - (node:14032) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
0|hitchhik | [2018-06-01 09:29:23.264] [ERROR] console - (node:14032) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
0|hitchhik | [2018-06-01 11:41:53.237] [ERROR] console - Error: read ECONNRESET
0|hitchhik |     at _errnoException (util.js:1022:11)
0|hitchhik |     at TCP.onread (net.js:628:25)
0|hitchhik | [2018-06-04 20:40:24.334] [ERROR] console - Error: read ECONNRESET
0|hitchhik |     at _errnoException (util.js:1022:11)
0|hitchhik |     at TCP.onread (net.js:628:25)
0|hitchhik | [2018-06-07 10:36:18.985] [ERROR] console - Error: read ECONNRESET
0|hitchhik |     at _errnoException (util.js:1022:11)
0|hitchhik |     at TCP.onread (net.js:628:25)
0|hitchhik | [2018-06-11 09:36:14.044] [ERROR] console - Error: read ECONNRESET
0|hitchhik |     at _errnoException (util.js:1022:11)
0|hitchhik |     at TCP.onread (net.js:628:25)





是这个吗

**Comment by brookshi** [comment]
cryptojs.zip 这个是你手动拷进去的吗，压缩后就删掉吧

**Comment by poipo** [comment]
好的，谢谢
