### ISSUE TITLE
mac 突然连不上hitchhiker服务器

### ISSUE THREAD

**Issue by and015** [brookshi/Hitchhiker#241]
1、sudo docker-compose up -d
     curl http://localhost:8090/
     进行这两步操作，第一步没问题，第二步之后出现curl: (52) Empty reply from server
2、之前是正常的，能连上服务器，今天突然就连不上了。

**5. Environment（环境）:**
 - Hitchhiker Version（Hitchhiker版本）: hitchhiker-cn:v0.14
 - Use Docker or Installation Package（使用Docker还是安装包）:Docker
 - Node Version if use installation package（如果使用安装包的Node版本） v8.11.3
 - Server OS （部署的系统）: MacOS
 - Browser（浏览器）Chrome

**Comment by brookshi** [comment]
容器有没有起来呢，sudo docker logs hitchhiker 看log呢

**Comment by and015** [comment]
容器已经起来了  log如下：
[2018-07-30T06:57:08.191Z] PM2 log: App name:index id:0 online
Error: EACCES: permission denied, mkdir '/usr/src/Hitchhiker/build/global_data/project/b2a0a550-8fe7-11e8-9309-511f4d090ce3-Sklt2tnSEX/lib'
    at Object.fs.mkdirSync (fs.js:895:18)
    at ProjectDataService.initFolderFiles (/usr/src/Hitchhiker/api/services/project_data_service.ts:164:16)
    at projectFolders.forEach.folder (/usr/src/Hitchhiker/api/services/project_data_service.ts:175:18)
    at Array.forEach (native)
    at ProjectDataService.initProjectFiles (/usr/src/Hitchhiker/api/services/project_data_service.ts:174:24)
    at new ProjectDataService (/usr/src/Hitchhiker/api/services/project_data_service.ts:31:14)
    at Object.<anonymous> (/usr/src/Hitchhiker/api/services/project_data_service.ts:19:43)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by and015** [comment]
确实有个错误，但应该怎样修改呢

**Comment by brookshi** [comment]
没权限创建这个目录：/usr/src/Hitchhiker/build/global_data/project/b2a0a550-8fe7-11e8-9309-511f4d090ce3-Sklt2tnSEX/lib，给project目录权限试试

**Comment by and015** [comment]
我这边usr下没有project目录   但我创建不了这个目录   也就没法给权限了

**Comment by brookshi** [comment]
这个是容器里的目录，应该是之前有上传lib吧，现在用新的镜像后会自动用host已有的lib在容器里创建。
要不你就先删掉/my/hitchhiker/data这个目录吧

**Comment by and015** [comment]
已经删掉了/my/hitchhiker/data这个目录   那下一步操作呢

**Comment by and015** [comment]
删掉之后再运行还是会报错，log如下
[2018-07-30T07:47:27.184Z] PM2 log: App name:index id:0 online
Error: ENOENT: no such file or directory, scandir '/usr/src/Hitchhiker/build/global_data/project'
    at Object.fs.readdirSync (fs.js:914:18)
    at ProjectDataService.initProjectFiles (/usr/src/Hitchhiker/api/services/project_data_service.ts:173:35)
    at new ProjectDataService (/usr/src/Hitchhiker/api/services/project_data_service.ts:31:14)
    at Object.<anonymous> (/usr/src/Hitchhiker/api/services/project_data_service.ts:19:43)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

**Comment by brookshi** [comment]
要删掉容器，再sudo docker-compose up -d

**Comment by and015** [comment]
删掉容器？？？具体操作是怎样的   不太会

**Comment by and015** [comment]
非常感谢您   可以重新登录了

**Comment by and015** [comment]
今天还是会出现相同的服务器连不上的问题    log显示目录没权限   虽说可以通过您昨天提供的方案重新登录进去   但每天都需要进行这个操作感觉挺麻烦的   如何在容器中找到目录并给与权限

**Comment by and015** [comment]
今天还是会出现相同的服务器连不上的问题    log显示目录没权限   虽说可以通过您昨天提供的方案重新登录进去   但每天都需要进行这个操作感觉挺麻烦的   如何在容器中找到目录并给与权限
