### ISSUE TITLE
ubuntu上安装后，启动报错Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by 317174106** [brookshi/Hitchhiker#66]
按照流程安装后，启动就报错了，大神能帮看看看错在哪里吗？

PM2的报错日志如下：

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ctrip/program/Hitchhiker/api/utils/script_transform.ts:1:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ctrip/program/Hitchhiker/api/utils/script_transform.ts:1:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ctrip/program/Hitchhiker/api/utils/script_transform.ts:1:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
Error: Cannot find module 'typescript

**Comment by brookshi** [comment]
少了typescript，是不是少执行了一个命令 `npm link typescript`

**Comment by 317174106** [comment]
是node没升级的问题，已经解决了

但现在启动后，页面上又报了一个错：
{"success":false,"message":"this api does not exist"}

**Comment by brookshi** [comment]
在哪个页面哪个api呢， 浏览器控制台的log麻烦截个图

**Comment by 317174106** [comment]
我都改好配置文件以后，直接访问就报错了：

@brookshi 



![hitch](https://user-images.githubusercontent.com/25921468/34187920-bbbfc6c6-e56e-11e7-92e2-2e8ad3466678.JPG)

**Comment by brookshi** [comment]
登录界面都没出来，怀疑是配置没配好，方便加我微信不 (iwxiaot)，沟通方便些

**Comment by 317174106** [comment]
已加

**Comment by brookshi** [comment]
脚本npm link typescript 改为npm install typescript@2.3.3 --save， fixed
