### ISSUE TITLE
docker模式安装无法启动

### ISSUE THREAD

**Issue by fenghong007** [brookshi/Hitchhiker#76]
我用docker模式安装的，服务是起来了，但是点击首页没什么内容，显示的源代码只有这个：

`

  | <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="shortcut icon" href="./favicon.ico"><title>Hitchhiker API</title><link href="./static/css/main.b825d6e7.css" rel="stylesheet"></head><body><div id="root"></div><script type="text/javascript" src="./static/js/main.5d0feff5.js"></script></body></html>
-- | --

`

这会是什么原因？

**Comment by brookshi** [comment]
浏览器控制台有什么错误提示吗

**Comment by fenghong007** [comment]
浏览器提示：
`VM374:161 Uncaught DOMException: Failed to construct 'WebSocket': The port 6666 is not allowed.
    at new WrappedWebSocket (<anonymous>:161:21)
    at e.value (http://192.168.2.135:6611/static/js/main.5d0feff5.js:11:25141)
    at i (http://192.168.2.135:6611/static/js/main.5d0feff5.js:47:21303)
    at Object.<anonymous> (http://192.168.2.135:6611/static/js/main.5d0feff5.js:47:21837)
    at t (http://192.168.2.135:6611/static/js/main.5d0feff5.js:1:107)
    at Object.<anonymous> (http://192.168.2.135:6611/static/js/main.5d0feff5.js:40:6599)
    at t (http://192.168.2.135:6611/static/js/main.5d0feff5.js:1:107)
    at Object.<anonymous> (http://192.168.2.135:6611/static/js/main.5d0feff5.js:1:506)
    at t (http://192.168.2.135:6611/static/js/main.5d0feff5.js:1:107)
    at http://192.168.2.135:6611/static/js/main.5d0feff5.js:1:196
WrappedWebSocket @ VM374:161
value @ stress.ts:36
i @ store.ts:27
(anonymous) @ store.ts:40
t @ bootstrap 4b4061679ee6cabce2c1:19
(anonymous) @ index.tsx:4
t @ bootstrap 4b4061679ee6cabce2c1:19
(anonymous) @ main.5d0feff5.js:71
t @ bootstrap 4b4061679ee6cabce2c1:19
(anonymous) @ bootstrap 4b4061679ee6cabce2c1:39
(anonymous) @ bootstrap 4b4061679ee6cabce2c1:39`

我远程服务器6666端口没开的缘故？我在服务器上用nginx对6666端口代理了下，代理成6611

**Comment by brookshi** [comment]
看起来像是端口没开

**Comment by fenghong007** [comment]
我把docker-compose.yml文件里的端口全部还原为8080就可以使用了。

**Comment by brookshi** [comment]
如果要改端口，需要改三个地方，host外加两个映射端口

**Comment by fenghong007** [comment]
好的，非常感谢

**Comment by brookshi** [comment]
不客气
