### ISSUE TITLE
start the Hitchhiker server, keep loading.the log show :

### ISSUE THREAD

**Issue by zhanghang06** [brookshi/Hitchhiker#82]
[ERROR] default - { Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TCP.onread (net.js:620:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

**Comment by zhanghang06** [comment]
在Hitchhiker目录下，重新执行了pm2 start ./pm2.json 
问题解决

**Comment by brookshi** [comment]
👍
